name: ci

on:
  push:
    branches:
      - master
    tags-ignore:
      - v[0-9]+.[0-9]+.[0-9]+
  pull_request:
    branches:
      - "**"

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: 1.14
      - uses: golangci/golangci-lint-action@v2
        with:
          version: v1.32
      - run: make test
